# **Customer Market Basket Analysis**

## Business Problem

The Sales and Marketing leadership has asked if there is buying pattern for our customers.  By creating the market basket analysis the hope is to come up with a way to target products and discounts to customers to drive revenue.  

We will be using the rules based association model to understand the patterns.

In [ ]:
# Import important libraries
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [ ]:
# Importing Data to Google Colab
from google.colab import files
uploaded = files.upload()
import io
df = pd.read_csv(io.BytesIO(uploaded['Hos_data.csv']))

Saving Hos_data.csv to Hos_data (2).csv

In [ ]:
df.head()

,Invoice_No,5x100mm,5x125mm,5x150mm,5x60mm,5x80mm,6x100mm,6x125mm,6x150mm,6x60mm,6x80mm,7x100mm,7x125mm,7x150mm,7x60mm,7x80mm
0,22701170,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1
1,22701087,0,0,0,0,0,1,1,1,0,1,1,1,1,1,1
2,22701474,0,0,0,0,0,1,0,1,1,0,0,1,1,1,1
3,22700438,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1
4,22701681,0,0,1,0,0,0,0,1,1,1,1,0,1,1,1

In [ ]:
df.isna().sum()

Invoice_No    0
5x100mm       0
5x125mm       0
5x150mm       0
5x60mm        0
5x80mm        0
6x100mm       0
6x125mm       0
6x150mm       0
6x60mm        0
6x80mm        0
7x100mm       0
7x125mm       0
7x150mm       0
7x60mm        0
7x80mm        0
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 956 entries, 0 to 955
Data columns (total 16 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Invoice_No  956 non-null    int64
 1   5x100mm     956 non-null    int64
 2   5x125mm     956 non-null    int64
 3   5x150mm     956 non-null    int64
 4   5x60mm      956 non-null    int64
 5   5x80mm      956 non-null    int64
 6   6x100mm     956 non-null    int64
 7   6x125mm     956 non-null    int64
 8   6x150mm     956 non-null    int64
 9   6x60mm      956 non-null    int64
 10  6x80mm      956 non-null    int64
 11  7x100mm     956 non-null    int64
 12  7x125mm     956 non-null    int64
 13  7x150mm     956 non-null    int64
 14  7x60mm      956 non-null    int64
 15  7x80mm      956 non-null    int64
dtypes: int64(16)
memory usage: 119.6 KB

In [ ]:
df1 = df.set_index('Invoice_No')

In [ ]:
def encode_units(x):
  if x <= 0:
    return 0
  if x >= 1:
    return 1

In [ ]:
basket_encode_plus = df1.applymap(encode_units)
basket_encode_plus

,5x100mm,5x125mm,5x150mm,5x60mm,5x80mm,6x100mm,6x125mm,6x150mm,6x60mm,6x80mm,7x100mm,7x125mm,7x150mm,7x60mm,7x80mm
Invoice_No,,,,,,,,,,,,,,,
22701170,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1
22701087,0,0,0,0,0,1,1,1,0,1,1,1,1,1,1
22701474,0,0,0,0,0,1,0,1,1,0,0,1,1,1,1
22700438,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1
22701681,0,0,1,0,0,0,0,1,1,1,1,0,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22700519,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
22700686,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
22700783,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
21700977,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
22700390,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0

In [ ]:
basket_filter_plus = basket_encode_plus[(basket_encode_plus > 0).sum(axis=1) >= 2]
basket_filter_plus

,5x100mm,5x125mm,5x150mm,5x60mm,5x80mm,6x100mm,6x125mm,6x150mm,6x60mm,6x80mm,7x100mm,7x125mm,7x150mm,7x60mm,7x80mm
Invoice_No,,,,,,,,,,,,,,,
22701170,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1
22701087,0,0,0,0,0,1,1,1,0,1,1,1,1,1,1
22701474,0,0,0,0,0,1,0,1,1,0,0,1,1,1,1
22700438,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1
22701681,0,0,1,0,0,0,0,1,1,1,1,0,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22700678,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0
22700379,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0
22700623,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0
22701073,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0
22700133,1,0,0,1,1,1,0,0,0,0,0,0,0,0,0

In [ ]:
from mlxtend.frequent_patterns import apriori

In [ ]:
frequent_itemsets_plus = apriori(basket_filter_plus, min_support=0.03, use_colnames=True).sort_values('support', ascending=False).reset_index(drop=True)

In [ ]:
frequent_itemsets_plus['length'] = frequent_itemsets_plus['itemsets'].apply(lambda x: len(x))

frequent_itemsets_plus

       support                                           itemsets  length
0     0.439189                                          (6x150mm)       1
1     0.297297                                          (6x100mm)       1
2     0.277027                                           (6x60mm)       1
3     0.277027                                          (5x150mm)       1
4     0.266892                                           (6x80mm)       1
...        ...                                                ...     ...
1291  0.030405                (6x80mm, 6x100mm, 7x150mm, 6x125mm)       4
1292  0.030405                (6x125mm, 6x100mm, 7x150mm, 6x60mm)       4
1293  0.030405                (6x125mm, 6x100mm, 7x100mm, 6x60mm)       4
1294  0.030405                (6x125mm, 6x100mm, 6x150mm, 7x60mm)       4
1295  0.030405  (6x125mm, 5x60mm, 5x125mm, 5x80mm, 6x60mm, 6x8...       8

[1296 rows x 3 columns]

In [ ]:
from mlxtend.frequent_patterns import association_rules

In [ ]:
product_analysis = association_rules(frequent_itemsets_plus, metric='lift', min_threshold=1).sort_values('lift', ascending=False).reset_index(drop=True)

In [ ]:
df_prod = pd.DataFrame(product_analysis)

In [ ]:
df_prod.head()

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,"(6x125mm, 5x60mm, 5x80mm, 5x100mm)","(5x125mm, 6x60mm, 5x150mm)",0.040541,0.033784,0.033784,0.833333,24.666667,0.032414,5.797297
1,"(5x100mm, 5x125mm, 6x60mm)","(6x125mm, 5x60mm, 5x80mm, 6x80mm, 5x150mm)",0.040541,0.030405,0.030405,0.750000,24.666667,0.029173,3.878378
2,"(6x125mm, 5x60mm, 5x80mm, 5x100mm)","(6x80mm, 5x125mm, 6x60mm, 5x150mm)",0.040541,0.030405,0.030405,0.750000,24.666667,0.029173,3.878378
3,"(6x80mm, 5x125mm, 6x60mm, 5x150mm)","(6x125mm, 5x60mm, 5x80mm, 5x100mm)",0.030405,0.040541,0.030405,1.000000,24.666667,0.029173,inf
4,"(5x125mm, 6x60mm, 5x150mm)","(6x125mm, 5x60mm, 5x80mm, 5x100mm)",0.033784,0.040541,0.033784,1.000000,24.666667,0.032414,inf

The support column tell us what percentage of the product mix applied to antecedents and consequents.  It is a good way for marketing personnel to understand what the customers buying pattern is.

In [ ]:
df_prod.to_csv('product_analysis.csv', encoding = 'utf-8-sig') 
files.download('product_analysis.csv')